export default {
  light: {
    primary: '#5E75F2',
    lightBlue1: '#668CD9',
    lightBlue2: '#73B2D9',
    lightGreen: '#73BFAA',
    text: '#333',
    profileText: '#FFF',
    background: '#FFFFFF',
    tint: '#5E75F2',
    tabIconDefault: '#ccc',
    tabIconSelected: '#5E75F2',
    icon: '#fff',
    secondaryText : '#808080',
  },
  dark: {
    primary: '#5E75F2',
    lightBlue1: '#668CD9',
    lightBlue2: '#73B2D9',
    lightGreen: '#73BFAA',
    text: '#fff',
    profileText: '#FFF',
    background: '#000',
    tint: '#5E75F2',
    tabIconDefault: '#ccc',
    tabIconSelected: '#5E75F2',
    icon: '#fff',
    secondaryText : '#fff',
  },
};